id: P006810
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17543
  title: བློ་བཟང་བཀྲ་ཤིས་རབ་རྒྱས་ཀྱི་རྣམ་པར་ཐར་པ།
  author: ''
  volumes:
    1e48233850dc486a9c7929f8e947ec6a:
      image_group_id: I8LS17560
      title: ''
      volume_number: 1
      total_pages: 130
