id: ID5B4254B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T01:23:44+00:00'
last_modified: '2022-06-08T07:00:53.038597+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17543
  title: བློ་བཟང་བཀྲ་ཤིས་རབ་རྒྱས་ཀྱི་རྣམ་པར་ཐར་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4288':
      image_group_id: I8LS17560
      title: ''
      total_pages: 130
      order: 1
      base_file: 4288.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
